### ISSUE TITLE
感谢您制作的mod,请允许我提出以下几点建议:

### ISSUE THREAD

**Issue by apeng0907** [nexor-source/TeleportYourself#1]
1.加入配置文件，可以自定义传送按键
2.加入一个选项，一局只能使用一次。
3.添加一个选项，按键之后先掉落所有物品。
4.添加一个选项，修改传送器价格为0。

**Comment by nexor-source** [comment]
> 1.加入配置文件，可以自定义传送按键 2.加入一个选项，一局只能使用一次。 3.添加一个选项，按键之后先掉落所有物品。 4.添加一个选项，修改传送器价格为0。

@apeng0907 感谢您提出的意见。
针对您的建议1，我添加了自定义的传送按键，但目前似乎只支持填入大写的英文字母。
针对您的建议2，我添加了CD的设定，默认是240秒的间隔时间。
针对您的建议3，我不是太明白这么做的意义是什么，传送本身会掉落身上的所有物品，这样修改似乎只是提前了几秒掉落身上的物品，因此我没有进行相关的调整
针对您的建议4，我认为传送器本身就会在比较前期就出出来，如果想要0元的传送器最好还是使用更多的金钱，开局自带传送器或者零元购之类的mod，修改传送器的价格对于这个传送mod来说似乎有一些出格了，如果这真的很必要的话我会考虑在之后更新它的。总之我暂时没有加入这种功能的打算。

**Comment by nexor-source** [comment]
@apeng0907  该mod由于仅客户端打了就可以生效，并且被认为过于作弊，已被管理员下架

**Comment by apeng0907** [comment]
啊这。能不能单独发给我一份0.2版本的1017443513@qq.om。或者你更新一下，改成房主有才能用，房主没加能进房但是功能不会生效，并且配置参数会自动同步为房主的设置。我需要这个的原因是因为自己制作了一个感染者模式的整合包，想作为幸存者和感染者同时拥有的技能配合使用。非常感谢您的回复。

**Comment by nexor-source** [comment]
@apeng0907 release中已更新 v 0.0.2 的文件，和房主同步的想法挺好的，可惜我暂时还不太会做

**Comment by nexor-source** [comment]
@apeng0907 复活赛打赢了，现在可以在雷电商城直接下载到了，CD是内置的240秒。
