### ISSUE TITLE
在终端输入传送的按键会触发传送

### ISSUE THREAD

**Issue by apeng0907** [nexor-source/TeleportYourself#2]

**Comment by apeng0907** [comment]
可以添加你的联系方式吗？QQ或者微信

**Comment by apeng0907** [comment]
当我将LocalFlashlight更新至最新版本时，会使TeleportYourself失效

**Comment by nexor-source** [comment]
已更新v 0.0.8版本，现在在打字以及终端不会触发传送功能了。
另外，我尝试了安装LocalFlashlight模组，但其并没有影响TeleportYourself的功能，我注意到LocalFlashlight模组有默认对F键绑定一个功能，请检查是否是因为LocalFlashlight默认的功能键F和您设定的TeleportYourself的传送键重复了。

**Comment by nexor-source** [comment]
> 当我将LocalFlashlight更新至最新版本时，会使TeleportYourself失效

@apeng0907 
已更新v 0.0.8版本，现在在打字以及终端不会触发传送功能了。
另外，我尝试了安装LocalFlashlight模组，但其并没有影响TeleportYourself的功能，我注意到LocalFlashlight模组有默认对F键绑定一个功能，请检查是否是因为LocalFlashlight默认的功能键F和您设定的TeleportYourself的传送键重复了。

**Comment by nexor-source** [comment]
> 可以添加你的联系方式吗？QQ或者微信

@apeng0907  wx号：g-old-city
